name: General CD

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  semantic_release:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
        name: Setup dotnet ${{ matrix.dotnet-version }}
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
        name: Setup cache for NuGet dependencies
      - uses: TriPSs/conventional-changelog-action@v5.2.0
        name: Conventional changelog action
        with:
          version-file: ./version.json
          skip-commit: true
        id: changelog
      - uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}